"""The query engine, the themes and the information maps - Phase 16g, measured.

16f said whether the map would load. This says whether it can be asked
questions about itself, and the three claims under test are the ones a filter
engine is usually only asserted to have:

    every filter fires   a map written here has exactly one province that each
                         filter must match, and every filter is checked against
                         the set it has to return - not against "some result"
    an unaskable filter  a vocabulary the mod does not ship turns its filter off
    says which file      WITH THE FILE NAMED, and takes no part in a query, so
                         it can neither empty an `all` nor widen an `any`
    what is drawn is     the region-to-colour table the browser paints and the
    what is written      TGA Python writes come out of one Colouring, and the
                         exported file round-trips byte for byte

The stock game is the measurement for the second claim, exactly as it was in
16f: its ``data/`` is packed, ``descr_sm_factions.txt`` is not on disk, and a
reader that does not check offers a culture filter with nothing in it and a
culture map that is uniformly blank.

Five parts, the last two of which need a game install:

    1  the three small files nothing else in the toolkit reads
    2  a map written here: every filter, and the exact set it must return
    3  colours, ramps, borders and the TGA round trip
    4  every real map: the vocabulary, the timings, and what it finds
    5  the four routes over real HTTP

    python -m tests.test_mapquery
"""
import json
import shutil
import sys
import tempfile
import threading
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from PIL import Image

from tests import _realmod
from unittransfer import campmap, campstrat, config, mapquery, mapvocab
from unittransfer.maptga import TgaInfo, encode, read
from unittransfer.mod import Mod
from unittransfer.server import Handler, Registry, _Server

ok = []


def check(label, cond):
    ok.append(bool(cond))
    print(f"  [{'OK ' if cond else 'FAIL'}] {label}")


def names(regions):
    return sorted(r.name for r in regions)


# ---- 1) the three small files -----------------------------------------------
print("\n1) descr_sounds_music_types.txt, descr_mercenaries.txt, "
      "descr_win_conditions.txt")

MUSIC_TEXT = """; generated by Geomod
music_type eastern_european

regions Alpha_Province Beta_Province
regions Gamma_Province

factions england france

music_type greek
regions Delta_Province
"""
music = mapquery.parse_music_types(MUSIC_TEXT)
check("a wrapped `regions` line accumulates rather than replacing: "
      f"{music.get('eastern_european')}",
      music.get("eastern_european") == ["Alpha_Province", "Beta_Province",
                                        "Gamma_Province"])
check("a `factions` line is read past, not into the region list",
      "england" not in (music.get("eastern_european") or []))
check("and the second block is its own", music.get("greek") == ["Delta_Province"])

MERC_TEXT = """pool Mordor
\tregions Alpha_Province Beta_Province
\tunit dhow,\t\t\texp 1 cost 1000 replenish 0.05 - 0.10 max 1 initial 0
\tunit Gondor Osgiliath Archers,\texp 0 cost 480 replenish 0.03 max 2 initial 1

pool Harad
\tregions Gamma_Province
\tunit Corsairs\t\t\texp 1 cost 280 replenish 0.15 - 0.25 max 2 initial 2
"""
pools = mapquery.parse_mercenaries(MERC_TEXT)
check(f"two pools, with their regions: {[(p.name, p.regions) for p in pools]}",
      len(pools) == 2 and pools[0].regions == ["Alpha_Province", "Beta_Province"]
      and pools[1].regions == ["Gamma_Province"])
check("a unit's name is everything in front of `exp`, comma and all: "
      f"{pools[0].units}",
      pools[0].units == ["dhow", "Gondor Osgiliath Archers"])

WIN_TEXT = """sicily
hold_regions Alpha_Province
take_regions 50
outlive england russia
short_campaign hold_regions Beta_Province
take_regions 30
outlive england

denmark
hold_regions Gamma_Province
take_regions 30
"""
wins = mapquery.parse_win_conditions(WIN_TEXT)
check(f"two factions: {[w.faction for w in wins]}",
      [w.faction for w in wins] == ["sicily", "denmark"])
check("the long campaign and the short one are kept apart: "
      f"hold {wins[0].hold} / {wins[0].short_hold}, take {wins[0].take} / "
      f"{wins[0].short_take}",
      wins[0].hold == ["Alpha_Province"] and wins[0].short_hold == ["Beta_Province"]
      and wins[0].take == 50 and wins[0].short_take == 30)
check("everything after a short_campaign line stays in the short campaign "
      "until the next faction opens",
      wins[0].short_outlive == ["england"] and wins[0].outlive == ["england", "russia"])
check("and the next faction starts on the long campaign again",
      wins[1].hold == ["Gamma_Province"] and not wins[1].short_hold)


# ---- 2) a map written here ---------------------------------------------------
print("\n2) a map with one province per answer: every filter, and the set it "
      "must return")

#  A A A A B B B B      Three provinces and a row of sea. A is England's, walled
#  A A S A B B B B      and with a market. B is Milan's castle. C is the rebels'
#  A A A A B B S B      and has the port. Every filter below has exactly one
#  A A A A B B B B      province it is meant to return, so a filter that matched
#  C C C C C C C C      everything and a filter that worked would not look the
#  C C S C C C P C      same.
#  ~ ~ ~ ~ ~ ~ ~ ~
W, H = 8, 7
A, B, C, SEA = (10, 20, 30), (40, 50, 60), (70, 80, 90), (0, 90, 200)
MARK, PORT = mapvocab.SETTLEMENT_RGB, mapvocab.PORT_RGB
GRID = [[A, A, A, A, B, B, B, B],
        [A, A, MARK, A, B, B, B, B],
        [A, A, A, A, B, B, MARK, B],
        [A, A, A, A, B, B, B, B],
        [C, C, C, C, C, C, C, C],
        [C, C, MARK, C, C, C, PORT, C],
        [SEA] * 8]
SEA_PX = 2 * 6

TERRAIN = ("dimensions\n{\n\twidth  %d\n\theight  %d\n}\nheights\n{\n"
           "\tmin_sea_height  -100.000\n\tmax_land_height  1000.000\n}\n"
           "roughness\n{\n\tmin  50.000\n\tmax  200.000\n}\nfractal\n{\n"
           "\tmultiplier  0.500\n}\nlattitude\n{\n\tmin  22.000\n\tmax  56.000\n}\n"
           % (W, H))

#: One record per province, and every field a filter reads has a different
#: value in each: hidden resource, rebel tribe, farming, triumph and the
#: religion split are all three different things.
RECORDS = (
    "A_Province\r\n\tAtown\r\n\tengland\r\n\tbrigands\r\n\t10 20 30\r\n"
    "\tgold\r\n\t7\r\n\t4\r\n\treligions { catholic 100 }\r\n"
    "\r\nB_Province\r\n\tBtown\r\n\tmilan\r\n\tpirates\r\n\t40 50 60\r\n"
    "\tsilver\r\n\t3\r\n\t2\r\n\treligions { catholic 40 orthodox 60 }\r\n"
    "\r\nC_Province\r\n\tCtown\r\n\tslave\r\n\tpeasant_revolt\r\n\t70 80 90\r\n"
    "\ttimber\r\n\t0\r\n\t0\r\n\treligions { catholic 50 orthodox 50 }\r\n")

CLIMATES = ("climates\n{\n\tsandy_desert\n}\n"
            "climate sandy_desert\n{\n\tcolour 200 100 50\n\theat 4\n}\n")

STRAT_LINES = [
    "campaign imperial_campaign",
    "playable",
    "\tengland",
    "end",
    "unlockable",
    "end",
    "nonplayable",
    "\tslave",
    "end",
    "",
    "start_date 1080 summer",
    "end_date 1500 winter",
    "",
    "resource gold, 1, 5",
    "resource silver, 5, 4",
    "resource ivory, 2, 1",   # on C_Province's settlement pixel
    "",
    "faction england, balanced smith",
    "\tai_label default",
    "\tdenari 10000",
    "\tsettlement",
    "\t{",
    "\t\tlevel large_town",
    "\t\tregion A_Province",
    "\t\tyear_founded 0",
    "\t\tpopulation 4200",
    "\t\tplan_set default_set",
    "\t\tfaction_creator england",
    "\t\tbuilding",
    "\t\t{",
    "\t\t\ttype core_building stone_wall",
    "\t\t}",
    "\t\tbuilding",
    "\t\t{",
    "\t\t\ttype market market",
    "\t\t}",
    "\t}",
    "",
    "faction milan, balanced smith",
    "\tai_label default",
    "\tdenari 10000",
    "\tsettlement castle",
    "\t{",
    "\t\tlevel town",
    "\t\tregion B_Province",
    "\t\tyear_founded 0",
    "\t\tpopulation 900",
    "\t\tplan_set default_set",
    "\t\tfaction_creator england",
    "\t}",
    "",
    "faction slave, comfort caesar",
    "\tai_label default",
    "\tdenari 1000",
    "\tsettlement",
    "\t{",
    "\t\tlevel village",
    "\t\tregion C_Province",
    "\t\tyear_founded 0",
    "\t\tpopulation 400",
    "\t\tplan_set default_set",
    "\t\tfaction_creator slave",
    "\t\tbuilding",
    "\t\t{",
    "\t\t\ttype port port",
    "\t\t}",
    "\t}",
    "",
    "faction_standings england, -0.5 slave",
    "",
    "script",
    "campaign_script.txt",
    "",
]
STRAT = "\r\n".join(STRAT_LINES)

FACTIONS = (
    "faction\tengland\n\tculture northern_european\n\treligion catholic\n"
    "\tprimary_colour red 200, green 40, blue 40\n"
    "\tsecondary_colour red 255, green 255, blue 255\n\n"
    "faction\tmilan\n\tculture southern_european\n\treligion catholic\n"
    "\tprimary_colour red 40, green 200, blue 40\n"
    "\tsecondary_colour red 255, green 255, blue 255\n\n"
    "faction\tslave\n\tculture southern_european\n\treligion catholic\n"
    "\tprimary_colour red 0, green 0, blue 0\n"
    "\tsecondary_colour red 255, green 255, blue 255\n")

EDB = (";\nhidden_resources gold silver timber\n\n"
       "building core_building\n{\n\tlevels wooden_wall stone_wall\n\t{\n"
       "\t\twooden_wall requires factions { northern_european, }\n\t\t{\n"
       "\t\t\tcapability\n\t\t\t{\n\t\t\t}\n\t\t\tconstruction 1\n"
       "\t\t\tcost 400\n\t\t\tsettlement_min town\n\t\t\tupgrades\n"
       "\t\t\t{\n\t\t\t}\n\t\t}\n"
       "\t\tstone_wall requires factions { northern_european, }\n\t\t{\n"
       "\t\t\tcapability\n\t\t\t{\n\t\t\t}\n\t\t\tconstruction 1\n"
       "\t\t\tcost 400\n\t\t\tsettlement_min town\n\t\t\tupgrades\n"
       "\t\t\t{\n\t\t\t}\n\t\t}\n\t}\n\tplugins\n\t{\n\t}\n}\n\n"
       "building market\n{\n\tlevels market\n\t{\n"
       "\t\tmarket requires factions { northern_european, }\n\t\t{\n"
       "\t\t\tcapability\n\t\t\t{\n\t\t\t}\n\t\t\tconstruction 1\n"
       "\t\t\tcost 400\n\t\t\tsettlement_min village\n\t\t\tupgrades\n"
       "\t\t\t{\n\t\t\t}\n\t\t}\n\t}\n\tplugins\n\t{\n\t}\n}\n")

MUSIC = ("music_type eastern_european\n\nregions A_Province\n\n"
         "music_type greek\n\nregions B_Province C_Province\n")

MERCS = ("pool North\n\tregions A_Province\n"
         "\tunit Longbowmen\texp 0 cost 400 replenish 0.1 max 2 initial 1\n\n"
         "pool South\n\tregions B_Province C_Province\n"
         "\tunit Corsairs\texp 0 cost 300 replenish 0.1 max 2 initial 1\n")

WINS = ("england\nhold_regions B_Province\ntake_regions 20\n"
        "short_campaign hold_regions B_Province\ntake_regions 10\n")

NAMES = "".join(f"{{{k}}}{v}\r\n" for k, v in (
    ("A_Province", "Aland"), ("Atown", "Atown"),
    ("B_Province", "Bland"), ("Btown", "Btown"),
    ("C_Province", "Cland"), ("Ctown", "Ctown")))


def paint_img(w, h, fn, mode="RGB"):
    im = Image.new(mode, (w, h))
    im.putdata([fn(x, y) if mode == "RGB" else fn(x, y) + (255,)
                for y in range(h) for x in range(w)])
    return im


def write_tga(path, img, depth=32, image_type=10, desc=0x08):
    info = TgaInfo(image_type=image_type, width=img.width, height=img.height,
                   depth=depth, descriptor=desc)
    path.write_bytes(encode(img.convert(info.mode), info))


def tiny_mod(root: Path) -> Path:
    """One complete little mod: ten layers and every file a filter reads."""
    base = root / "data" / campmap.BASE_REL
    base.mkdir(parents=True, exist_ok=True)
    (base / "descr_terrain.txt").write_text(TERRAIN, encoding="latin-1")
    (base / "descr_regions.txt").write_bytes(RECORDS.encode("latin-1"))
    (base / "descr_sounds_music_types.txt").write_bytes(MUSIC.encode("latin-1"))
    write_tga(base / "map_regions.tga",
              paint_img(W, H, lambda x, y: GRID[y][x], "RGBA"))
    write_tga(base / "map_heights.tga",
              paint_img(2 * W + 1, 2 * H + 1,
                        lambda x, y: (0, 0, 200) if y >= SEA_PX else (90, 90, 90),
                        "RGBA"))
    write_tga(base / "map_ground_types.tga",
              paint_img(2 * W + 1, 2 * H + 1,
                        lambda x, y: (196, 0, 0) if y >= SEA_PX else (96, 160, 64),
                        "RGBA"))
    write_tga(base / "map_climates.tga",
              paint_img(2 * W + 1, 2 * H + 1, lambda x, y: (200, 100, 50), "RGBA"))
    write_tga(base / "map_features.tga",
              paint_img(W, H, lambda x, y: (0, 0, 0), "RGBA"))
    write_tga(base / "map_fog.tga",
              paint_img(2 * W + 1, 2 * H + 1, lambda x, y: (255, 255, 255)),
              depth=24, image_type=10, desc=0x00)
    write_tga(base / "map_trade_routes.tga",
              paint_img(W, H, lambda x, y: (0, 0, 0)), depth=24, desc=0x00)
    write_tga(base / "map_roughness.tga",
              paint_img(2 * W, 2 * H, lambda x, y: (0, 0, 0)), depth=24, desc=0x00)
    write_tga(base / "water_surface.tga",
              paint_img(2 * W + 1, 2 * H + 1, lambda x, y: (0, 0, 120)),
              depth=24, image_type=2, desc=0x20)

    data = root / "data"
    (data / mapvocab.CLIMATES_REL).write_text(CLIMATES, encoding="latin-1")
    (data / "descr_sm_factions.txt").write_bytes(FACTIONS.encode("latin-1"))
    (data / "export_descr_buildings.txt").write_bytes(EDB.encode("latin-1"))
    camp = data / campstrat.CAMPAIGN_DIR_REL / campstrat.DEFAULT_CAMPAIGN
    camp.mkdir(parents=True, exist_ok=True)
    (camp / campstrat.STRAT_NAME).write_bytes(STRAT.encode("latin-1"))
    (camp / mapquery.MERCS_NAME).write_bytes(MERCS.encode("latin-1"))
    (camp / mapquery.WIN_NAME).write_bytes(WINS.encode("latin-1"))
    (data / "text").mkdir(parents=True, exist_ok=True)
    (data / campmap.REGION_NAMES_REL).write_bytes(
        b"\xff\xfe" + NAMES.encode("utf-16-le"))
    return base


cfg = Path(tempfile.mkdtemp(prefix="ut_cfg_"))
config.CONFIG_DIR = cfg
config.BACKUP_DIR = cfg / "backups"
config.SETTINGS_PATH = cfg / "settings.json"
config.LOG_PATH = cfg / "transfers.json"
config._cache_dir = cfg / "cache"                      # exports land here

tmp = Path(tempfile.mkdtemp(prefix="ut_query_"))
tiny_root = tmp / "mods" / "Tiny"
tiny_mod(tiny_root)
tiny = Mod(tiny_root)

facts = mapquery.Facts(tiny, campmap.CampaignMap(tiny))
check(f"the fact table joins all four sources in {facts.ms} ms, "
      f"{len(facts.regions)} provinces",
      len(facts.regions) == 3 and not facts.skipped)

a = facts.by_name["a_province"]
check("A_Province is joined right across every file: "
      f"{a.owner}/{a.culture}/{a.level}/{a.wall}/{a.music_type}/"
      f"{a.merc_pools}/{a.trade_resources}",
      a.owner == "england" and a.culture == "northern_european"
      and a.level == "large_town" and a.wall == "stone_wall"
      and a.music_type == "eastern_european" and a.merc_pools == ["North"]
      and a.trade_resources == ["gold"] and a.hidden_resources == ["gold"]
      and a.has_settlement_pixel and not a.has_port_pixel
      and a.building_lines == ["core_building", "market"])
c = facts.by_name["c_province"]
check(f"and C_Province has the port pixel and the port building: "
      f"{c.has_port_pixel}, {c.port_building}, owner {c.owner!r}",
      c.has_port_pixel and c.port_building == "port" and c.owner == "slave")
check("a province split 50/50 has no religion majority, and is not given one",
      c.religions == {"catholic": 50, "orthodox": 50} and c.religion_majority == "")

#: ``(filter, what is picked in it, the provinces it must return)``. One row per
#: filter, and every one names an exact set - a filter that matched everything
#: would fail here and would not fail against "some result came back".
WANT = [
    ({"code": "owner", "value": "england"}, ["A_Province"]),
    ({"code": "culture", "value": "southern_european"},
     ["B_Province", "C_Province"]),
    ({"code": "creator", "value": "milan"}, ["B_Province"]),
    ({"code": "settlement_creator", "value": "england"},
     ["A_Province", "B_Province"]),
    ({"code": "rebels", "value": "pirates"}, ["B_Province"]),
    ({"code": "win_condition", "value": "england"}, ["B_Province"]),
    ({"code": "hidden_resource", "value": "timber"}, ["C_Province"]),
    ({"code": "trade_resource", "value": "gold"}, ["A_Province"]),
    ({"code": "religion_majority", "value": "orthodox"}, ["B_Province"]),
    ({"code": "religion_share", "value": "catholic", "min": 50},
     ["A_Province", "C_Province"]),
    ({"code": "farming", "min": 3}, ["A_Province"]),
    ({"code": "triumph", "min": 3, "max": 7}, ["A_Province", "B_Province"]),
    ({"code": "music_type", "value": "greek"}, ["B_Province", "C_Province"]),
    ({"code": "mercenary_pool", "value": "North"}, ["A_Province"]),
    ({"code": "has_port"}, ["C_Province"]),
    ({"code": "wall", "value": "stone_wall"}, ["A_Province"]),
    ({"code": "settlement_kind", "value": "castle"}, ["B_Province"]),
    ({"code": "level", "value": "village"}, ["C_Province"]),
    ({"code": "population", "min": 1000}, ["A_Province"]),
    ({"code": "building", "value": "market"}, ["A_Province"]),
    ({"code": "building_tree", "value": "core_building"}, ["A_Province"]),
    ({"code": "name", "value": "bland"}, ["B_Province"]),
    ({"code": "pixels", "min": 15}, ["A_Province", "B_Province"]),
    ({"code": "unsettled"}, []),
]
covered = {row[0]["code"] for row in WANT}
check(f"every one of the {len(mapquery.FILTERS)} filters has a row under test",
      covered == set(mapquery.FILTER_BY_CODE))
check("every filter carries a source, a group and one of the five kinds",
      all(f.source and f.group and f.label
          and f.kind in ("choice", "bool", "range", "text", "share")
          for f in mapquery.FILTERS))

for rule, want in WANT:
    got = mapquery.run_query(facts, [rule])
    label = rule["code"] + (f" = {rule['value']}" if rule.get("value") else "")
    label += f" >= {rule['min']}" if "min" in rule and not rule.get("value") else ""
    check(f"{label} returns exactly {want or 'nothing'}"
          + (f", got {names(got.matched)}" if names(got.matched) != want else ""),
          names(got.matched) == want and not got.off)

both = mapquery.run_query(facts, [{"code": "owner", "value": "england"},
                                  {"code": "has_port"}])
check("two filters under `all` is the intersection, which here is empty",
      not both.matched)
either = mapquery.run_query(facts, [{"code": "owner", "value": "england"},
                                    {"code": "has_port"}], match="any")
check(f"and under `any` it is the union: {names(either.matched)}",
      names(either.matched) == ["A_Province", "C_Province"])
negated = mapquery.run_query(facts, [{"code": "has_port", "negate": True}])
check(f"`not` keeps what the filter does not describe: {names(negated.matched)}",
      names(negated.matched) == ["A_Province", "B_Province"])
empty = mapquery.run_query(facts, [])
check("no filter at all matches nothing, rather than everything",
      not empty.matched)
why = mapquery.run_query(facts, [{"code": "trade_resource", "value": "gold"}])
check(f"and every match says why it is one: {why.why['A_Province']}",
      why.why["A_Province"] == ["Trade resource: gold"])


# ---- 3) colours, ramps, borders and the round trip ---------------------------
print("\n3) what is drawn and what is written come out of one table")

col = mapquery.colouring(facts, "faction")
check(f"the faction theme is one group per faction: "
      f"{[(g.key, g.rgb) for g in col.groups]}",
      len(col.groups) == 3
      and dict((g.key, g.rgb) for g in col.groups)["england"] == (200, 40, 40))
check("a faction whose declared colour is the settlement marker is swapped, "
      f"and the swap says what it clashed with: {col.substituted}",
      len(col.substituted) == 1 and col.substituted[0]["value"] == "slave"
      and col.substituted[0]["clash"] == "the settlement marker")
check("and no two groups end up within the readable gap of each other",
      all(mapquery._distance(x.rgb, y.rgb) >= mapquery.COLOUR_GAP
          for i, x in enumerate(col.groups) for y in col.groups[i + 1:]))

table = col.payload(facts)["colours"]
check("the table the browser paints is keyed by the region's MAP colour, "
      "which is what the label image has",
      table[str(campmap.key(A))] == [200, 40, 40]
      and table[str(campmap.key(B))] == [40, 200, 40])

img = mapquery.render(facts, col)
check(f"the picture is the size of map_regions.tga: {img.size}",
      img.size == (W, H))
px = img.load()
check("a province takes its group's colour, the sea takes the backdrop and a "
      "settlement pixel keeps its own",
      px[0, 0] == (200, 40, 40) and px[0, 6] == mapquery.BACKDROP
      and px[2, 1] == mapvocab.SETTLEMENT_RGB)
check("the border is drawn where two groups meet and nowhere inside one",
      px[3, 0] == mapquery.BORDER and px[0, 1] != mapquery.BORDER)

flat = mapquery.render(facts, col, borders=False)
check("and with borders off there is not one border pixel anywhere",
      mapquery.BORDER not in set(flat.get_flattened_data()))

ex = mapquery.export_colouring(facts, "faction")
check(f"an export writes one TGA into the cache: {ex.files}",
      ex.files and Path(ex.folder).is_file() is False
      and (Path(ex.folder) / ex.files[0]["name"]).is_file())
back, info = read(Path(ex.folder) / ex.files[0]["name"])
check("in the shape of the mod's own map_regions.tga, and the same picture "
      "as the one on screen, pixel for pixel",
      (info.width, info.height) == (W, H)
      and list(back.convert("RGB").get_flattened_data())
      == list(img.get_flattened_data()))

batch = mapquery.export_factions(facts)
check(f"the batch writes one file per faction plus the map they are all on: "
      f"{[f['name'] for f in batch.files]}",
      len(batch.files) == 4
      and batch.files[0]["name"] == "map_all_factions.tga"
      and all((Path(batch.folder) / f["name"]).is_file() for f in batch.files))

agri = mapquery.colouring(facts, "agriculture")
check(f"a magnitude map has fixed bands, low to high: "
      f"{[(g.label, len(g.regions)) for g in agri.groups]}",
      len(agri.groups) == 6
      and [len(g.regions) for g in agri.groups] == [1, 0, 1, 0, 1, 0])
check("the ramp's ends are its ends, and its middle is not one of them",
      mapquery.ramp(0) == mapquery._RAMP[0] and mapquery.ramp(1) == mapquery._RAMP[2]
      and mapquery.ramp(0.5) == mapquery._RAMP[1])
check("and no band of it is within the readable gap of the sea behind the map",
      all(mapquery._distance(g.rgb, mapquery.BACKDROP) >= mapquery.COLOUR_GAP
          for g in agri.groups))

one = mapquery.colouring(facts, "hidden:timber")
check(f"a per-resource map is presence, two groups: "
      f"{[(g.key, len(g.regions)) for g in one.groups]}",
      [len(g.regions) for g in one.groups] == [1, 2])
cat = {c["code"] for c in mapquery.catalogue(facts)}
check(f"the catalogue lists one map per hidden resource, religion and trade "
      f"resource actually on the map: {len(cat)} in all",
      {"hidden:gold", "hidden:timber", "religion:orthodox", "trade:ivory"} <= cat)
try:
    mapquery.colouring(facts, "nonsense")
    refused = False
except campmap.MapError:
    refused = True
check("a theme code nothing declares is refused by name", refused)


# ---- 4) every real map -------------------------------------------------------
print("\n4) every installed map: the vocabulary, the timings, and what it finds")

roots = _realmod.installed()
game = _realmod.MODS.parent
if (game / "data" / campmap.BASE_REL / "descr_terrain.txt").exists():
    roots.append(game)
roots = [r for r in roots
         if (r / "data" / campmap.BASE_REL / "descr_terrain.txt").exists()]

if not roots:
    print("  SKIPPED - no installed mod (and no game) with a campaign map")
else:
    for root in roots:
        mod = Mod(root)
        print(f"\n  -- {mod.name}")
        f = mapquery.Facts(mod, campmap.CampaignMap(mod))
        v = mapquery.vocab(f)
        warm = mapquery.Facts(mod, campmap.CampaignMap(mod))
        check(f"the fact table joins {len(f.regions)} provinces in {f.ms} ms "
              f"cold and {warm.ms} ms once the mod's own caches are warm - the "
              f"cold half is parsing this mod's export_descr_buildings.txt, "
              f"which the buildings browser pays for too and shares",
              f.ms < 3000 and warm.ms < 1000)
        for s in f.skipped:
            print(f"     not read - {s['what']}: {s['why'][:84]}")
        live = [x for x in v["filters"] if not x["off"]]
        print(f"     {len(live)} of {len(v['filters'])} filters live, "
              f"{len(v['colourings'])} colourings")
        check("every filter that is off names the file that would run it, and "
              "every filter that is live has something to pick",
              all(x["off"] for x in v["filters"] if not x["values"]
                  and x["kind"] == "choice")
              and all(len(x["off"]) > 20 for x in v["filters"] if x["off"]))

        # the three the phase's exit criteria name
        owners = [x for x in v["filters"] if x["code"] == "owner"][0]
        if owners["values"]:
            who = owners["values"][0]["value"]
            got = mapquery.run_query(f, [{"code": "owner", "value": who}])
            check(f"an owner query works: {who} starts with "
                  f"{len(got.matched)} province(s)",
                  len(got.matched) == owners["values"][0]["count"])
        res = [x for x in v["filters"] if x["code"] == "trade_resource"][0]
        if res["values"]:
            what = res["values"][0]["value"]
            got = mapquery.run_query(f, [{"code": "trade_resource", "value": what}])
            check(f"a resource query works: {what} is in {len(got.matched)} "
                  f"province(s)", len(got.matched) == res["values"][0]["count"])
        rel = [x for x in v["filters"] if x["code"] == "religion_majority"][0]
        if rel["values"]:
            which = rel["values"][0]["value"]
            got = mapquery.run_query(f, [{"code": "religion_majority",
                                          "value": which}])
            check(f"a religion-majority query works: {which} leads in "
                  f"{len(got.matched)} province(s)",
                  len(got.matched) == rel["values"][0]["count"])

        for code in ("faction", "religion", "agriculture", "population"):
            got = mapquery.colouring(f, code)
            if got.off:
                print(f"     {code} is off - {got.off[:80]}")
                continue
            drawn = mapquery.render(f, got)
            check(f"the {code} map draws at {drawn.size[0]}x{drawn.size[1]} "
                  f"with {len(got.groups)} group(s)"
                  + (f", {len(got.substituted)} colour(s) swapped"
                     if got.substituted else ""),
                  drawn.size == (f.cm.terrain.width, f.cm.terrain.height))

    if (game / "data" / campmap.BASE_REL / "descr_terrain.txt").exists():
        f = mapquery.Facts(Mod(game), campmap.CampaignMap(Mod(game)))
        v = mapquery.vocab(f)
        cult = [x for x in v["filters"] if x["code"] == "culture"][0]
        check("the stock game keeps descr_sm_factions.txt inside its packed "
              "data, so the culture filter is OFF with that file named rather "
              "than empty: " + cult["off"][:70],
              cult["off"] and "descr_sm_factions.txt" in cult["off"])
        got = mapquery.run_query(f, [{"code": "culture", "value": "greek"},
                                     {"code": "has_port"}])
        check(f"and a query holding it does not run it at all: "
              f"{len(got.matched)} matched on the port alone, "
              f"{len(got.off)} filter(s) not asked",
              len(got.off) == 1 and got.off[0]["code"] == "culture"
              and got.matched and all(r.has_port_pixel for r in got.matched))
        trees = mapquery.run_query(f, [{"code": "building_tree",
                                        "value": "core_building"}])
        check(f"the building-tree filter still runs with no EDB on disk, off "
              f"descr_strat.txt's own words: {len(trees.matched)} province(s)",
              trees.matched)


# ---- 5) the routes -----------------------------------------------------------
print("\n5) /api/map/query/vocab, /api/map/colouring, /api/map/query, /api/map/export")

med2 = Path(tempfile.mkdtemp(prefix="ut_med2_"))
http_root = med2 / "mods" / "QueryMod"
http_root.mkdir(parents=True)
shutil.copytree(tiny_root / "data", http_root / "data")
config.save_settings(med2_root=str(med2), run_full_cleaner=False)

Handler.registry = Registry(cfg / "icons")
srv = _Server(("127.0.0.1", 0), Handler)
base_url = f"http://127.0.0.1:{srv.server_address[1]}"
threading.Thread(target=srv.serve_forever, daemon=True).start()
print(f"  serving {base_url}")


def get(path):
    with urllib.request.urlopen(base_url + path, timeout=30) as r:
        return json.load(r)


def post(path, body):
    req = urllib.request.Request(
        base_url + path, data=json.dumps(body).encode(),
        headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


try:
    v = get("/api/map/query/vocab?mod=QueryMod")
    check(f"/api/map/query/vocab answers with {len(v['filters'])} filters and "
          f"{len(v['colourings'])} colourings in {v['ms']} ms",
          len(v["filters"]) == len(mapquery.FILTERS) and v["regions"] == 3)

    r = post("/api/map/query", {"mod": "QueryMod",
                                "rules": [{"code": "has_port"}]})
    check(f"/api/map/query answers with the set, the reasons and the colours: "
          f"{[x['name'] for x in r['regions']]}",
          r["count"] == 1 and r["regions"][0]["name"] == "C_Province"
          and r["colours"][str(campmap.key(C))] == list(mapquery.HIGHLIGHT))
    check("and the table dims every province that did NOT match rather than "
          "leaving it as it was, which is what the exported TGA does too",
          len(r["colours"]) == 3
          and r["colours"][str(campmap.key(A))] == list(mapquery.NO_GROUP))

    r = get("/api/map/colouring?mod=QueryMod&code=religion")
    check(f"/api/map/colouring answers with the legend and the table: "
          f"{[g['label'] for g in r['groups']]}",
          r["borders"] and len(r["colours"]) == 3
          and sum(g["regions"] for g in r["groups"]) == 2)

    r = get("/api/map/colouring?mod=QueryMod&code=not_a_map")
    check("an unknown colouring is a 404 with the name in it, not a blank map",
          False)
except urllib.error.HTTPError as e:
    check("an unknown colouring is a 404 with the name in it, not a blank map",
          e.code == 404 and "not_a_map" in e.read().decode())

try:
    r = post("/api/map/export", {"mod": "QueryMod", "what": "factions"})
    check(f"/api/map/export writes Geomod's batch: {r['count']} files, "
          f"{r['bytes']} bytes",
          r["count"] == 4 and all((Path(r["folder"]) / f["name"]).is_file()
                                  for f in r["files"]))
    r = post("/api/map/export", {"mod": "QueryMod", "what": "query",
                                 "rules": [{"code": "has_port"}]})
    check("and the query result as one TGA", r["count"] == 1)
    r = post("/api/map/export", {"mod": "QueryMod", "what": "query",
                                 "rules": [{"code": "owner", "value": "nobody"}]})
    check(f"a query that matched nothing is refused with a reason rather than "
          f"a blank file: {r.get('error', '')[:60]}",
          r["count"] == 0 and r.get("error"))
finally:
    srv.shutdown()
    srv.server_close()

shutil.rmtree(med2, ignore_errors=True)
shutil.rmtree(tmp, ignore_errors=True)
shutil.rmtree(cfg, ignore_errors=True)

print(f"\n{sum(ok)}/{len(ok)} checks - "
      + ("ALL PASSED" if all(ok) else f"{len(ok) - sum(ok)} FAILED"))
sys.exit(0 if all(ok) else 1)
