"""Phase 87h. The map bundle: a campaign map as one zip in Mylae's layout.

His New Map Editor ends in *Export Bundle*, ``m2tw_map_layers.zip``: each
layer's TGA at the top of the zip under the game's own file name, and a
``reference/`` folder beside them holding ``map_regions.txt`` (a province a
line: its name, its colour, its city's pixel and its port's), the historic
features as ``historic_features.txt`` and one transparent PNG a tag, and
whatever reference pictures were made. This writes the same zip from a map
on disk, so a map made or changed here can be taken into his editor, or kept.

**The layers are the files on disk, byte for byte.** His are re-encoded from
the canvas and, for a turned box, resampled onto the map's rectangle at
export. Here the turn is in the projection (87a), so every layer already is
the map's rectangle, and the bundle copies each file as it is: every one of
the ten layers the map has (his six and the four he does not draw). A paint
stroke not yet saved is not in them; the page says so before it asks.

**``bbox_coords.txt``** goes at the top beside the layers, with the rotation,
because his Campaign Map reads it by name out of a folder of map files and
lines the OSM backdrop up with it.

**``reference/map_regions.txt``** is his columns: ``name  r g b  city_x city_y
port_x port_y``, pixels counted from the regions map's top-left, ``0 0`` for a
province with no port (his), ``-1 -1`` for one with no city (his value for a
point he could not place). The province is every one the map paints that
``descr_regions.txt`` declares, in the engine's order. His header line has a
long dash, and here it has a hyphen; it is a comment.

**The historic sites** are whatever 87f already fetched for this box, read off
disk: making a bundle sends nothing to Overpass. A reference picture is the
one thing that can use the network (87b's tiles, under 25's switch), and only
when asked for.
"""
from __future__ import annotations

import io
import zipfile
from typing import Dict, List, Optional

from PIL import Image

from . import campmap, osmmap, osmsites

REF = "reference"


def regions_text(cm) -> str:
    """His ``map_regions.txt`` for the map as it stands on disk."""
    lines = ["; map_regions.txt - generated by the Medieval 2 GUI Toolkit",
             "; province_name  r g b  city_x city_y  port_x port_y", ""]
    regs = [r for r in cm.index.regions if r.record is not None and r.pixels]
    regs.sort(key=lambda r: (r.region_id < 0, r.region_id))
    for r in regs:
        cx, cy = r.settlement if r.settlement else (-1, -1)
        px, py = r.port if r.port else (0, 0)
        red, green, blue = r.rgb
        lines.append(f"{r.name}  {red} {green} {blue}  {cx} {cy}  {px} {py}")
    return "\n".join(lines)


def kept_sites(box: osmmap.Bbox) -> Dict[str, List[dict]]:
    """Every historic tag already fetched for this box, off disk; nothing is
    asked. ``{}`` when none was."""
    tags = [t for t in osmsites.BY_KEY
            if any(r.get("kind") == "historic" and t in r.get("meta", {}).get("tags", [])
                   for r in osmmap.fetches_for(box))]
    return osmsites.fetch(box, tags) if tags else {}


def tag_png(found: Dict[str, List[dict]], tag: str, proj: osmmap.Projection) -> bytes:
    """His per-tag layer: transparent, the map's size, one pixel a site in the
    tag's colour."""
    img = Image.new("RGBA", (proj.w, proj.h), (0, 0, 0, 0))
    rgb = osmsites.colour(*tag.split("=", 1))
    for s in osmsites.sites({tag: found[tag]}, proj):
        if s["on_map"]:
            img.putpixel((s["x"], s["y"]), tuple(rgb) + (255,))
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return buf.getvalue()


def build(cm, picture: Optional[str] = None, year=None, picture_px: int = 2048) -> dict:
    """The zip, and what is in it: ``{data, name, files: [{name, size}], notes}``."""
    w, h = cm.terrain.width, cm.terrain.height
    box, _ = osmmap.box_for(cm)
    out = io.BytesIO()
    files, notes = [], []
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        def put(name, data):
            z.writestr(name, data)
            files.append({"name": name, "size": len(data)})

        for ly in campmap.LAYERS:
            path = cm.path(ly["code"])
            if path.is_file():
                put(ly["file"], path.read_bytes())
            elif ly["required"]:
                notes.append(f"{ly['file']} is missing from the map, so it is not in the bundle")
        if box is not None:
            put(osmmap.BBOX_FILE, osmmap.bbox_text(box, w, h))
        else:
            notes.append("the map has no real-world box, so there is no bbox_coords.txt "
                         "and no historic sites")
        put(f"{REF}/map_regions.txt", regions_text(cm))
        if box is not None:
            proj = osmmap.Projection(box, w, h)
            found = kept_sites(box)
            if found:
                put(f"{REF}/historic_features.txt", osmsites.features_text(found, proj))
                for t in found:
                    put(f"{REF}/{t.replace('=', '_')}.png", tag_png(found, t, proj))
            if picture:
                img = osmmap.picture(box, w, h, picture, year, picture_px)
                buf = io.BytesIO()
                img.save(buf, "PNG", optimize=True)
                put(f"{REF}/reference_{picture}_{w}x{h}.png", buf.getvalue())
    return {"data": out.getvalue(), "name": f"{cm.mod.name}_map_layers.zip",
            "files": files, "notes": notes}
