"""The campaign folder's three small files - Phase 18a: M5, M6 and G3.

    M5  data/text/campaign_descriptions.txt   what the menu calls the campaign
    M6  descr_faction_movies.xml              the intro and victory movies
    G3  descr_mercenaries.txt                 which pool a province draws on

Four claims, and the last one is the one that had a bug under it:

    the key is built, not listed   IMPERIAL_CAMPAIGN_SICILY_TITLE comes from the
                                   campaign folder's name and the faction's, so
                                   a mod that renamed both is still readable
    every file comes back          parse(t).text() == t on every installed mod,
                                   including the two that end without a newline
    a slot is a line               a movie slot that is not there is a line
                                   added in order, and one cleared is a line
                                   removed - never <victory></victory>
    a regions line is variable      keyblock.sub_tokens walks the tokens already
                                   on a line, so a shorter list would leave the
                                   provinces past its end still on it. Moving a
                                   province out of a pool has to remove the word

Five parts:

    1  the description keys, and the view over them
    2  faction movies: parse, edit, add, delete, check
    3  mercenary pools: move a province, and the short-list case
    4  every installed mod: round trip and what it finds
    5  plan and apply against a copy of a real mod

    python -m tests.test_campfiles
"""
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tests import _realmod, _tmp
from unittransfer import campfiles as cf
from unittransfer import stringsbin
from unittransfer.mod import Mod

ok = []


def check(label, cond):
    ok.append(bool(cond))
    print(f"  [{'OK ' if cond else 'FAIL'}] {label}")


codes = lambda fs: sorted({f["code"] for f in fs})

# both real files end WITHOUT a trailing newline, which is why this one does too
MOVIES = ('<?xml version="1.0" encoding="utf-8" ?> \r\n'
          "<faction_movies>\r\n"
          "\t<faction>\r\n"
          "\t\t<name>england</name>\r\n"
          "\t\t<intro>faction/major_intro.bik</intro>\r\n"
          "\t\t<victory>faction/england_win.bik</victory>\r\n"
          "\t</faction>\r\n"
          "\t<faction>\r\n"
          "\t\t<name>slave</name>\r\n"
          "\t\t<defeat>faction/minor_lose.bik</defeat>\r\n"
          "\t</faction>\r\n"
          "</faction_movies>")

MERCS = ("; generated by Geomod\n"
         "\n"
         "pool Britain\n"
         "\tregions England_Province Wales_Province Scotland_Province\n"
         "\tunit Peasants\t\texp 0 cost 100 replenish 0.05 - 0.1 max 2 initial 1\n"
         "\n"
         "pool Iberia\n"
         "\tregions Spain_Province\t; the only one\n"
         "\tunit Jinetes\t\texp 0 cost 200 replenish 0.05 - 0.1 max 2 initial 1\n"
         "\n"
         "pool Empty\n"
         "\tunit Mercs\t\texp 0 cost 100 replenish 0.05 - 0.1 max 1 initial 0\n")


# ---- 1) the description keys -------------------------------------------------
print("\n1) campaign_descriptions.txt - the key is built from two names")

check("the campaign's own title",
      cf.descr_key("imperial_campaign", "", "TITLE")
      == "IMPERIAL_CAMPAIGN_TITLE")
check("a faction's title",
      cf.descr_key("imperial_campaign", "sicily", "TITLE")
      == "IMPERIAL_CAMPAIGN_SICILY_TITLE")
check("a faction's blurb",
      cf.descr_key("imperial_campaign", "papal_states", "DESCR")
      == "IMPERIAL_CAMPAIGN_PAPAL_STATES_DESCR")
check("a campaign folder that is not lower case",
      cf.descr_key("Fellowship_Campaign", "england", "TITLE")
      == "FELLOWSHIP_CAMPAIGN_ENGLAND_TITLE")
check("the two suffixes are the only two the real files use",
      cf.DESCR_KINDS == ("TITLE", "DESCR"))


# ---- 2) faction movies -------------------------------------------------------
print("\n2) descr_faction_movies.xml")

mf = cf.parse_movies(MOVIES)
check("the file comes back byte for byte, trailing newline and all",
      mf.text() == MOVIES)
check("both blocks are read",
      [r.faction for r in mf.records] == ["england", "slave"])
check("a slot that is there is read",
      mf.get("england").get("victory") == "faction/england_win.bik")
check("a slot that is not there is known to be absent",
      not mf.get("england").as_dict()["defeat_set"])
check("the closing tag is found", mf.close_line == len(mf.lines) - 1)
check("nothing is warned about a sound file", mf.warnings == [])

one = cf.render_movies(mf, mf.get("england"),
                       {"victory": "faction/new_win.bik"})
check("editing one slot rewrites one line",
      sum(1 for a, b in zip(MOVIES.split("\r\n"), one.split("\r\n")) if a != b) == 1)
check("…and the file still ends without a newline", not one.endswith("\n"))
check("…and the tab indent is the file's own",
      "\t\t<victory>faction/new_win.bik</victory>" in one)

grown = cf.render_movies(mf, mf.get("england"), {"defeat": "faction/lose.bik"})
after = cf.parse_movies(grown)
check("a slot that was not there is added",
      after.get("england").get("defeat") == "faction/lose.bik")
check("…in the order the real files write the slots",
      [s for s in cf.MOVIE_SLOTS if s in after.get("england").lines]
      == ["intro", "victory", "defeat"])
check("…and it lands after victory, not at the end of the block",
      after.get("england").lines["defeat"] < after.get("england").end - 1)

cleared = cf.parse_movies(cf.render_movies(mf, mf.get("england"), {"victory": ""}))
check("a slot cleared loses its line rather than becoming <victory></victory>",
      "victory" not in cleared.get("england").lines
      and "<victory>" not in cleared.text())

added = cf.parse_movies(cf.insert_movie_block(
    mf, cf.new_movie_block("france", {"intro": "faction/fr.bik"})))
check("a new block lands above </faction_movies>",
      [r.faction for r in added.records] == ["england", "slave", "france"]
      and added.close_line == len(added.lines) - 1)
check("…and carries only the slots it was given",
      list(added.get("france").lines) == ["intro"])

removed = cf.parse_movies(cf.remove_movie_block(mf, mf.get("slave")))
check("deleting a block takes exactly its own lines",
      [r.faction for r in removed.records] == ["england"]
      and removed.text() == MOVIES.replace(
          "\t<faction>\r\n\t\t<name>slave</name>\r\n"
          "\t\t<defeat>faction/minor_lose.bik</defeat>\r\n\t</faction>\r\n", ""))

fs = cf.check_movies(cf.parse_movies(MOVIES), None, "imperial_campaign",
                     ["england"])
check("a block for a faction the campaign does not start is reported",
      "unknown_faction" in codes(fs))
check("…and the rule does not run at all with no faction list",
      "unknown_faction" not in codes(
          cf.check_movies(cf.parse_movies(MOVIES), None, "imperial_campaign", None)))

twice = MOVIES.replace("<name>slave</name>", "<name>england</name>")
check("a faction with two blocks is reported",
      "duplicate" in codes(cf.check_movies(cf.parse_movies(twice))))

empty = MOVIES.replace("\t\t<defeat>faction/minor_lose.bik</defeat>\r\n", "")
check("a block that names no movie at all is reported",
      "no_movies" in codes(cf.check_movies(cf.parse_movies(empty))))


# ---- 3) mercenary pools ------------------------------------------------------
print("\n3) descr_mercenaries.txt - moving a province between pools")

xf = cf.parse_mercs(MERCS)
check("the file comes back byte for byte", xf.text() == MERCS)
check("the pools come from mapquery's parser, not a second one",
      [p.name for p in xf.pools] == ["Britain", "Iberia", "Empty"])
check("a province knows which pool it is in",
      xf.pool_of("Wales_Province") == "Britain")
check("a province in no pool says so", xf.pool_of("Nowhere_Province") == "")

moved = cf.parse_mercs(cf.move_region(xf, "Wales_Province", "Iberia"))
check("moving a province puts it in the new pool",
      moved.pool_of("Wales_Province") == "Iberia")
check("…and TAKES IT OUT of the old one - the short-list case",
      "Wales_Province" not in [r for p in moved.pools if p.name == "Britain"
                               for r in p.regions])
check("…rewriting two lines and nothing else",
      sum(1 for a, b in zip(MERCS.split("\n"), moved.text().split("\n"))
          if a != b) == 2)
check("…and the trailing comment on the line survives",
      "; the only one" in moved.text())

out = cf.parse_mercs(cf.move_region(xf, "Spain_Province", ""))
check("taking a province out of every pool leaves it in none",
      out.pool_of("Spain_Province") == "")
check("…and a pool with nothing left loses its regions line rather than "
      "keeping an empty one",
      out.regions_line["Iberia"] == -1 and "regions \n" not in out.text()
      and "regions\t" not in out.text().replace("\tregions", ""))

into = cf.parse_mercs(cf.move_region(xf, "Wales_Province", "Empty"))
check("a pool that never had a regions line is given one",
      into.pool_of("Wales_Province") == "Empty")

same = cf.move_region(xf, "Wales_Province", "Britain")
check("moving a province to the pool it is already in changes nothing",
      same == MERCS)

try:
    cf.move_region(xf, "Wales_Province", "NoSuchPool")
    refused = False
except cf.CampFileError:
    refused = True
check("a pool that does not exist is refused", refused)

fs = cf.check_mercs(xf, ["England_Province", "Wales_Province",
                         "Scotland_Province", "Spain_Province", "Lonely_Province"])
check("a pool with no regions line is reported", "no_regions" in codes(fs))
check("a province in no pool is reported", "no_pool" in codes(fs))
check("…and with no region list, neither province rule runs",
      "no_pool" not in codes(cf.check_mercs(xf, None))
      and "unknown_region" not in codes(cf.check_mercs(xf, None)))
both = MERCS.replace("\tregions Spain_Province",
                     "\tregions Spain_Province Wales_Province")
check("a province in two pools is reported",
      "two_pools" in codes(cf.check_mercs(cf.parse_mercs(both))))


# ---- 4) every installed mod --------------------------------------------------
print("\n4) every campaign folder on this machine")

swept = 0
for root in _realmod.installed():
    mod = Mod(root)
    for camp in cf.campaigns(mod):
        swept += 1
        head = f"{root.name}/{camp}"
        try:
            m, text = cf.read_movies(mod, camp)
        except cf.CampFileError:
            m = None
        if m is not None:
            check(f"{head}: {len(m.records)} movie block(s) come back byte for byte",
                  m.text() == text)
            check(f"{head}: every block re-renders to itself unchanged",
                  all(cf.render_movies(m, r, {}) == text for r in m.records))
            check(f"{head}: the movie file warns about nothing", m.warnings == [])
        try:
            x, xtext = cf.read_mercs(mod, camp)
        except cf.CampFileError:
            x = None
        if x is not None:
            check(f"{head}: {len(x.pools)} merc pools come back byte for byte",
                  x.text() == xtext)
            first = next((p for p in x.pools if p.regions), None)
            if first is not None:
                r = first.regions[0]
                there = cf.move_region(x, r, "")
                back = cf.move_region(cf.parse_mercs(there), r, first.name)
                check(f"{head}: taking `{r}` out and putting it back is a round trip",
                      cf.parse_mercs(back).pool_of(r) == first.name)
        v = cf.descr_view(mod, camp)
        check(f"{head}: {v['keys']} description keys, "
              f"{len(v['rows'])} factions, title {v['title']!r}",
              bool(v["rows"]) and bool(v["title"]))
        named = sum(1 for row in v["rows"] if row["title"])
        print(f"       {named}/{len(v['rows'])} factions have a menu title")
print(f"  swept {swept} campaign(s)")


# ---- 5) plan and apply -------------------------------------------------------
print("\n5) a save against a copy of a real mod")

src = _realmod.pick("Third_Age_Reforged", need="text/campaign_descriptions.txt")
tmp = Path(_tmp.mkdtemp(prefix="ut_campfiles_"))
dest = tmp / src.name
camp = cf.DEFAULT_CAMPAIGN
(dest / "data" / "text").mkdir(parents=True)
(dest / "data" / cf.CAMPAIGN_DIR_REL / camp).mkdir(parents=True)
for rel in (cf.DESCR_REL, cf.DESCR_REL + ".strings.bin"):
    if (src / "data" / rel).exists():
        shutil.copy2(src / "data" / rel, dest / "data" / rel)
mrel = f"{cf.CAMPAIGN_DIR_REL}/{camp}/{cf.MOVIES_NAME}"
xrel = f"{cf.CAMPAIGN_DIR_REL}/{camp}/{cf.MERCS_NAME}"
for rel in (mrel, xrel):
    if (src / "data" / rel).exists():
        shutil.copy2(src / "data" / rel, dest / "data" / rel)
mod = Mod(dest)

# --- M5
txt_before = (dest / "data" / cf.DESCR_REL).read_bytes()
bin_before = (dest / "data" / (cf.DESCR_REL + ".strings.bin")).read_bytes()
p = cf.plan(mod, {"what": "descriptions", "campaign": camp, "name": "sicily",
                  "edits": {"title": "Gondor Reborn"}})
check("a description save plans one key", p.payload()["ok"]
      and list(p.loc_writes) == ["IMPERIAL_CAMPAIGN_SICILY_TITLE"])
check("nothing is written by a plan",
      (dest / "data" / cf.DESCR_REL).read_bytes() == txt_before)
res = cf.apply(p)
check("the .txt is written",
      (dest / "data" / cf.DESCR_REL).read_bytes() != txt_before)
check("…and the compiled archive beside it is rebuilt, not left stale",
      (dest / "data" / (cf.DESCR_REL + ".strings.bin")).read_bytes() != bin_before)
pairs = cf.descr_pairs(mod)
check("the key reads back as it was typed",
      pairs["IMPERIAL_CAMPAIGN_SICILY_TITLE"] == "Gondor Reborn")
compiled = stringsbin.load_pairs(
    stringsbin.bin_path_for(dest / "data" / cf.DESCR_REL))
check("…and the game would read the same thing out of the .bin",
      compiled["IMPERIAL_CAMPAIGN_SICILY_TITLE"] == "Gondor Reborn")
check("both files are in the backup set",
      len(res["record"]["manifest"]["backed_up"]) == 2)
check("the backup of the .txt is byte-exact",
      (Path(res["record"]["backup_root"]) / "data"
       / cf.DESCR_REL).read_bytes() == txt_before)
check("the log records it as a campfiles job",
      res["record"]["mode"] == "campfiles"
      and res["record"]["options"]["what"] == "descriptions")

# The blurb is a paragraph on ONE line of the file: the codec unescapes `\n` on
# the way in, so the textarea shows real line breaks, and a save has to put them
# back as the two characters or the record ends mid-paragraph and the rest of it
# becomes a continuation of the key.
para = cf.plan(mod, {"what": "descriptions", "campaign": camp, "name": "sicily",
                     "edits": {"descr": "Line one\nLine two"}})
cf.apply(para)
raw = (dest / "data" / cf.DESCR_REL).read_text(encoding=cf.LOC_ENCODING)
key = cf.descr_key(camp, "sicily", "DESCR")
row = next(ln for ln in raw.splitlines() if ln.lstrip("﻿").startswith("{" + key + "}"))
check("a blurb with a line break in it is written as one line",
      row.endswith("Line one\\nLine two"))
check("…and reads back as a real line break",
      cf.descr_pairs(mod)[key] == "Line one\nLine two")

fresh = cf.plan(mod, {"what": "descriptions", "campaign": camp,
                      "name": "no_such_faction", "edits": {"title": "New"}})
check("a key the file has not got is created rather than refused",
      fresh.payload()["ok"] and fresh.loc_new
      == ["IMPERIAL_CAMPAIGN_NO_SUCH_FACTION_TITLE"])

# --- M6
if (dest / "data" / mrel).exists():
    before = (dest / "data" / mrel).read_bytes()
    m, _ = cf.read_movies(mod, camp)
    who = m.records[0].faction
    p = cf.plan(mod, {"what": "movies", "campaign": camp, "name": who,
                      "edits": {"intro": "faction/test_intro.bik"}})
    check("a movie save plans one change", p.payload()["ok"]
          and len(p.changes) == 1)
    cf.apply(p)
    m2, now = cf.read_movies(mod, camp)
    check("the slot is written",
          m2.get(who).get("intro") == "faction/test_intro.bik")
    check("…and it is still the same file with one line more",
          len(now.splitlines()) == len(before.decode("latin-1").splitlines()) + 1)
    gone = cf.plan(mod, {"what": "movies", "campaign": camp, "name": who,
                         "action": "delete"})
    cf.apply(gone)
    m3, _ = cf.read_movies(mod, camp)
    check("deleting the block takes only that block",
          m3.get(who) is None and m3.close_line >= 0)

# --- G3
if (dest / "data" / xrel).exists():
    before = (dest / "data" / xrel).read_bytes()
    x, _ = cf.read_mercs(mod, camp)
    pool = next(p for p in x.pools if p.regions)
    other = next(p for p in x.pools if p.name != pool.name)
    region = pool.regions[0]
    p = cf.plan(mod, {"what": "mercenaries", "campaign": camp, "name": region,
                      "edits": {"pool": other.name}})
    check("a pool move plans one change", p.payload()["ok"]
          and len(p.changes) == 1)
    cf.apply(p)
    x2, _ = cf.read_mercs(mod, camp)
    check("the province is in the new pool", x2.pool_of(region) == other.name)
    check("…and out of the old one",
          region not in next(q.regions for q in x2.pools if q.name == pool.name))
    back = cf.plan(mod, {"what": "mercenaries", "campaign": camp, "name": region,
                         "edits": {"pool": pool.name}})
    cf.apply(back)
    x3, _ = cf.read_mercs(mod, camp)
    check("putting it back restores every pool's membership",
          {q.name: sorted(q.regions) for q in x3.pools}
          == {q.name: sorted(q.regions) for q in x.pools})
    # not byte-exact, and it should not be asserted to be: a `regions` line is
    # a set, the file records no position for a province within it, so a
    # province that leaves a pool and returns comes back at the end of the list.
    # Every other line is untouched, which is the claim worth making.
    now = (dest / "data" / xrel).read_bytes()
    check("…changing one line of the file and no other",
          sum(1 for a, b in zip(before.decode("latin-1").splitlines(),
                                now.decode("latin-1").splitlines())
              if a != b) == 1)
    v = cf.mercs_view(mod, camp, region)
    check("the picker knows every pool and which one this province is in",
          v["have"] and v["pool"] == pool.name
          and len(v["pools"]) == len(x.pools))


print(f"\n{sum(ok)}/{len(ok)} checks"
      + (" - ALL PASSED" if all(ok) else f" - {ok.count(False)} FAILED"))
sys.exit(0 if all(ok) else 1)
